sudo: false
language: generic

addons:
  apt:
    packages:
      - libgmp-dev

env:
  matrix:
    - GHCVER=7.10 STACK_YAML=stack-7.10.yaml
    - GHCVER=8.0 STACK_YAML=stack-8.0.yaml
    - GHCVER=8.2 STACK_YAML=stack-8.2.yaml
    - GHCVER=8.4 STACK_YAML=stack.yaml

install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --no-terminal --version

script:
  - stack setup --no-terminal
  - stack update --no-terminal
  - stack build -j2 --fast --no-terminal
  - travis_wait 45 sleep 1800 &
  - stack test --fast --no-terminal

cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true
